#!/bin/sh
# Makefile header-dep freshness regression.
#
# accd/Makefile carries an inline header-dep block (regenerated by
# 'make depend' which runs cc -MM on every .c).  When a #include is
# added or removed in any .c or .h, the block goes stale: incremental
# builds quietly skip translation units that should rebuild, leading
# to a struct-layout-corruption crash (lobby.h grew, only lobby.o
# rebuilt, accd segfaulted on first connect -- caught 2026-05-13).
#
# This test asserts the inline block matches the freshly-generated
# 'make depend' output: any divergence means someone changed an
# include but didn't refresh the Makefile.
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
cd "$HERE/.."/..

# Extract the inline block between sentinels.  Drop leading/trailing
# whitespace so the awk-friendly continuation lines compare cleanly.
extract_inline() {
    awk '
        /^# --- header deps begin ---$/ {capture=1; next}
        /^# --- header deps end ---$/   {capture=0}
        capture
    ' Makefile
}

inline=$(extract_inline)
fresh=$(make -s depend 2>/dev/null)

if [ -z "$inline" ]; then
    echo "FAIL: Makefile has no '--- header deps begin/end ---' sentinel block"
    exit 1
fi
if [ -z "$fresh" ]; then
    echo "FAIL: 'make depend' produced no output"
    exit 2
fi

# Normalize: join `\`-continuation lines, collapse whitespace, sort
# (cc -MM may wrap at different column widths across invocations
# even when the dependency set is identical).
canon() {
    awk 'BEGIN{ORS=""} /\\$/ {sub(/\\$/,""); printf "%s",$0; next} {print $0 "\n"}' "$@" \
        | sed -e 's/[[:space:]]\+/ /g' -e 's/^ //' -e 's/ $//' \
        | sort
}

i_tmp=$(mktemp); f_tmp=$(mktemp)
trap 'rm -f "$i_tmp" "$f_tmp"' EXIT
printf '%s\n' "$inline" | canon > "$i_tmp"
printf '%s\n' "$fresh"  | canon > "$f_tmp"

if diff -u "$i_tmp" "$f_tmp" >/dev/null; then
    echo "RESULT: PASS (inline header deps match 'make depend' output)"
    exit 0
fi

echo "FAIL: inline header-deps block in Makefile is stale."
echo "      Run 'make depend' and paste the output between the"
echo "      '# --- header deps begin ---' / '# --- header deps end ---'"
echo "      sentinel comments.  Diff (inline -> fresh):"
diff -u "$i_tmp" "$f_tmp" | head -40
exit 3
